# report.py
import os
from logger import log_event

def generate_report():
    lines = []
    lines.append("===== BURGER SHOP REPORT =====")
    lines.append("Generated by System")
    lines.append("")

    def count_records(file_path, size):
        if not os.path.exists(file_path):
            return 0
        with open(file_path, 'rb') as f:
            data = f.read()
            return len(data) // size

    lines.append(f"Total Products: {count_records('products.dat', 38)}")
    lines.append(f"Total Prices: {count_records('prices.dat', 23)}")
    lines.append(f"Total Promotions: {count_records('promotions.dat', 34)}")
    lines.append("")

    with open("report.txt", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log_event("SYSTEM", "Generate report", "OK", "report.txt created")
    print("Report generated as 'report.txt'")
